package vdfp

// generated by peg2go shell script

import (
	"encoding/base64"
)

var grammar string

func getGrammar() (string, error) {
	if grammar != "" {
		return grammar, nil
	}

	b64 := "Um9vdCA8LSAoTm9kZSAvIEtWcykrCgojLy8gTm9kZSAob2JqZWN0KQpOb2RlIDwtIFMqIEtleSBOIFMqICJ7IiBOIChOb2RlKyAvIEtWcyspIFMqICJ9IiBOCgojLy8gS2V5L1ZhbHVlCktWcyA8LSBTKiBLZXkgUysgVmFsdWUgTgoKS2V5IDwtICJcIiIgKCAhIlwiIiAuICkqICJcIiIKClZhbHVlIDwtICJcIiIgKCAhIlwiIiAuICkqICJcIiIKCiMvLyBCYXNpY3MKCiMvLyBXaGl0ZXNwYWNlIGJ1dCBub3QgRU9MClMgIDwtICAiICIgLyBUCgojLy8gVGFidWxhdGlvbgpUIDwtIFtcdF0KCiMvLyBOZXdsaW5lCk4gPC0gKFtcbl0gLyBbXHJdIC8gW1xyXG5dKSsKClRrKHgpIDwtIDwgeCA+Cg=="

	data, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		return "", err
	}

	grammar = string(data)
	return grammar, err
}
